const SECRET_KEY = '5yWELJFexPR3KHTLzZckcFmwukgHc6djBIqaQqTFVvnTuPGRfy5nhz7cWJG6'
const JWT_LIFE_TIME = 60 * 60 * 24 * 7

const PAGE_RECORDS = 24
const PAGE_LIST = 48

module.exports = {SECRET_KEY, JWT_LIFE_TIME, PAGE_LIST, PAGE_RECORDS}