export const PERSON_TEMPERATURE_MIN = 36.4
export const PERSON_TEMPERATURE_MAX = 36.8
export const PERSON_OXYGEN_MIN = 95
export const PERSON_OXYGEN_MAX = 100
export const PERSON_HEART_RATE_MIN = 60
export const PERSON_HEART_RATE_MAX = 70
